Repository cremich/kiko-backend, pull requests merged in 2021-04, with the labels that each got.

#2 Github Sponsoring
  .github/FUNDING.yml
Labels: good first issue

#8 feat: adds dependabot
  .github/dependabot.yml
Labels: enhancement

#6 fix: add missing dependencies for build
  package-lock.json
  package.json
Labels: question

#25 Provide some meaningful unit tests for dynamodb tables
  lib/pool-management/stack.ts
  lib/shared/constructs/dynamodb-table.ts
  test/pool-management/__snapshots__/stack.test.ts.snap
  test/pool-management/stack.test.ts
  test/shared/constructs/dynamodb-table.test.ts
Labels: enhancement

#29 Get rid of user pool domain
  bin/kiko.ts
  lib/tenant-management/stack.ts
  package-lock.json
Labels: bug

#30 Bump cdk version to 1.100.0
  package-lock.json
  package.json
Labels: dependencies

#32 fix(#31): adds required node and npm version to readme
  README.md
Labels: documentation

#35 task: configure alarm on CampaignSendMessagePermanentFailure metric
  README.md
  bin/kiko.ts
  lib/shared/constructs/alarm-infra.ts
  lib/tenant-management/constructs/tenant.ts
  lib/tenant-management/stack.ts
  package-lock.json
  package.json
  test/shared/constructs/alarm-infra.test.ts
Labels: enhancement
